GET http://localhost:9999/api/posts

###

POST http://localhost:9999/api/posts
Content-Type: application/json

{
  "id": 3,
  "content": "Last Post number n"
}

###

DELETE http://localhost:9999/api/posts/0

###

GET http://localhost:9999/api/posts/0